name: "basic"

components:
  - name: "caddy"
    type: pod
    ports:
      - host: 8080
        container: 80
    containers:
      - name: "caddy"
        image: "caddy:latest"
        command: ["caddy", "file-server", "--root", "/srv/www"]
        volumes:
          - host: "./examples/basic/assets/www"
            container: "/srv/www"

global:
  scripts:
    - "./examples/basic/tests.rhai"
  module_dirs:
    - "./examples/basic/modules"
  keep_running: false
  delay: "0s"
  repeat: 1
  filter: null
  skip: null 
  reset_once: false
  force: false
